# Contains elements from params.h

from typing import List

KYBER_K = 3

assert KYBER_K in [2, 3, 4] and "KYBER_K must be in {2, 3, 4}"

KYBER_N = 256
KYBER_Q = 3329

KYBER_SYMBYTES  = 32   # size in bytes of hashes, and seeds
KYBER_SSBYTES   = 32   # size in bytes of shared key

KYBER_POLYBYTES	    = 384
KYBER_POLYVECBYTES  = (KYBER_K * KYBER_POLYBYTES)

if KYBER_K == 2:
    KYBER_ETA1 = 3
    KYBER_POLYCOMPRESSEDBYTES    = 128
    KYBER_POLYVECCOMPRESSEDBYTES = (KYBER_K * 320)
elif KYBER_K == 3:
    KYBER_ETA1 = 2
    KYBER_POLYCOMPRESSEDBYTES    = 128
    KYBER_POLYVECCOMPRESSEDBYTES = (KYBER_K * 320)
elif KYBER_K == 4:
    KYBER_ETA1 = 2
    KYBER_POLYCOMPRESSEDBYTES    = 160
    KYBER_POLYVECCOMPRESSEDBYTES = (KYBER_K * 352)

KYBER_ETA2 = 2

KYBER_INDCPA_MSGBYTES       = (KYBER_SYMBYTES)
KYBER_INDCPA_PUBLICKEYBYTES = (KYBER_POLYVECBYTES + KYBER_SYMBYTES)
KYBER_INDCPA_SECRETKEYBYTES = (KYBER_POLYVECBYTES)
KYBER_INDCPA_BYTES          = (KYBER_POLYVECCOMPRESSEDBYTES + KYBER_POLYCOMPRESSEDBYTES)

KYBER_PUBLICKEYBYTES  = (KYBER_INDCPA_PUBLICKEYBYTES)
# 32 bytes of additional space to save H(pk)
KYBER_SECRETKEYBYTES  = (KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + 2*KYBER_SYMBYTES)
KYBER_CIPHERTEXTBYTES = (KYBER_INDCPA_BYTES)

